[package]
name = "perf"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Native Perfetto recording and generated typed instrumentation."

[features]
default = ["native"]
native = ["dep:perfetto-sdk"]

[dependencies]
artifactfs.workspace = true
web-time = { workspace = true }
serde_json.workspace = true
uuid = { version = "1", features = ["v4"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "1", features = ["js"] }

[target.'cfg(unix)'.dependencies]
perfetto-sdk = { version = "1", optional = true }

[lints]
workspace = true
